server:
  port: 8080
spring:
  redis:
    host: localhost
    port: 6379
    database: 1
    password:
    timeout: 3000ms
    redisson:
      config: classpath:redisson.yml

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admin?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

logging:
  level:
    root: error
    demo.springboot: debug